#!/bin/bash -x
timestemp=`date +%F-%H%M%S`
devicenum=${DEV_NUM:-1}
NL=`echo -ne '\015'`
if [ -z ${devicenum} ];then
  devicenum=1
fi

screen_rc(){
  echo -e "${1}" >>/tmp/swift-screenrc
}

cat > /tmp/swift-screenrc << EOH
sessionname swift
hardstatus alwayslastline '%{= .} %-Lw%{= .}%> %n%f %t*%{= .}%+Lw%< %-=%{g}(%{d}%H/%l%{g})'
setenv PROMPT_COMMAND /bin/true
screen -t shell bash
screen -t s-proxy bash
stuff "/home/rminmin/openstack/swift/bin/swift-proxy-server /etc/swift/proxy-server.conf -v${NL}"
logfile /home/rminmin/openstack/logs/s-proxy.log.${timestemp}
log on
EOH
for i in `seq 1 ${devicenum}`;do
  cat >>/tmp/swift-screenrc << EOH
screen -t s-object-${i} bash
stuff "/home/rminmin/openstack/swift/bin/swift-object-server /etc/swift/object-server/${i}.conf -v$NL"
logfile /home/rminmin/openstack/logs/s-object-${i}.log.${timestemp}
log on
screen -t s-container-${i} bash
stuff "/home/rminmin/openstack/swift/bin/swift-container-server /etc/swift/container-server/${i}.conf -v$NL"
logfile /home/rminmin/openstack/logs/s-container-${i}.log.${timestemp}
log on
screen -t s-account-${i} bash
stuff "/home/rminmin/openstack/swift/bin/swift-account-server /etc/swift/account-server/${i}.conf -v$NL"
logfile /home/rminmin/openstack/logs/s-account-${i}.log.${timestemp}
log on
EOH
done
