#!/bin/bash -x
timestemp=`date +%F-%H%M%S`
NL=`echo -ne '\015'`

cat > /tmp/senlin-screenrc << EOH
sessionname senlin
hardstatus alwayslastline '%{= .} %-Lw%{= .}%> %n%f %t*%{= .}%+Lw%< %-=%{g}(%{d}%H/%l%{g})'
setenv PROMPT_COMMAND /bin/true
screen -t shell bash
screen -t senlin-engine bash
stuff "senlin-engine --config-file /etc/senlin/senlin.conf ${NL}"
logfile /home/rminmin/openstack/logs/senlin-engine.log.${timestemp}
log on
screen -t senlin-api bash
stuff "senlin-api --config-file /etc/senlin/senlin.conf ${NL}"
logfile /home/rminmin/openstack/logs/senlin-api.log.${timestemp}
log on
EOH
