#!/bin/bash
create_trove_instance(){
  trove create "$TROVENAME"  $TROVE_FLAVOR --datastore ${DATASTORE} --datastore_version ${DATASTORE_VERSION} --nic net-id=${NETID} --size 1
  # Timeout 10 minutes
  timeout=60
  echo "Wait Trove instance Active ..."
  while [ 1 -eq 1 ];do
      status=`trove list |grep  $TROVENAME | awk '{print $10}'`
      if [ -z $status ];then
        return 1
      fi
      if [ "$status" == "ACTIVE" ];then
           trove show $TROVENAME
           return 0
      fi
      sleep 10
      timeout=$(( timeout-1 ))
  done
  return 1
}

get_security_groups(){
  device_id=$1
  token=`openstack token issue | grep " id " | awk '{print $4}'`
  curl -X GET "http://127.0.0.1:9696/v2.0/ports.json?fields=security_groups&fields=id&device_id=${device_id}" -H "User-Agent: python-neutronclient" -H "Accept: application/json" -H "X-Auth-Token: ${token}" 2>/dev/null | $(dirname $0)/jq ".ports[0].security_groups[0]" | tr -d '"'
}

add_port_accessable(){
  port=$1
  sg_id=$2
  neutron security-group-rule-create  --protocol tcp --port-range-min $port --port-range-max $port --direction ingress --remote-ip-prefix 0.0.0.0/0 $sg_id
}

get_fixed_ip(){
  device_id=$1
  network_id=$2
  token=`openstack token issue | grep " id " | awk '{print $4}'`
  curl -X GET "http://127.0.0.1:9696/v2.0/ports.json?fields=fixed_ips&fields=id&device_id=${device_id}&network_id=${network_id}" -H "User-Agent: python-neutronclient" -H "Accept: application/json" -H "X-Auth-Token: ${token}" 2>/dev/null | $(dirname $0)/jq ".ports[0].fixed_ips[0].ip_address" | tr -d '"'
}

config_zabbix_server(){
  net_id=$1
  shift 1
  fixed_ip=$1
  shift 1
  key=$1
  shift 1
  ssh_cmd="ip netns exec qdhcp-$net_id ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $key centos@${fixed_ip}"
  $ssh_cmd "sudo ls -l /root/zabbix-scripts"
  $ssh_cmd "sudo /root/zabbix-scripts/config_zabbix_server.sh $*"
  $ssh_cmd "sudo systemctl restart httpd zabbix-server; sudo systemctl status httpd zabbix-server;"
}

config_zabbix_agent(){
  net_id=$1
  shift 1
  fixed_ip=$1
  shift 1
  key=$1
  shift 1
  server_ip=$1
  generate_zabbix_agent_template $server_ip $fixed_ip
  ip netns exec qdhcp-$net_id scp -i $key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $(dirname $0)/zabbix_agentd.conf ubuntu@${fixed_ip}:/home/ubuntu/zabbix_agentd.conf
  ssh_cmd="ip netns exec qdhcp-$net_id ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $key ubuntu@${fixed_ip}"
  $ssh_cmd "sudo mysql --defaults-file=/home/ubuntu/.my.cnf -e \"CREATE USER 'trove_monitor'@'localhost' IDENTIFIED BY 'troveMonitor1qa2ws!@#';grant select on *.* to trove_monitor@localhost; flush privileges;\""
  $ssh_cmd "sudo mv /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf.bak;sudo mv /home/ubuntu/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf;sudo cat /etc/zabbix/zabbix_agentd.conf;sudo service zabbix-agent restart;sudo service zabbix-agent status"
}

generate_zabbix_agent_template(){
  server_ip=$1
  listen_ip=$2
  sed "s/SERVERIP/${server_ip}/g;s/LISTENIP/${listen_ip}/g" $(dirname $0)/zabbix_agent.template | tee $(dirname $0)/zabbix_agentd.conf
}
