heat_template_version: 2013-05-23
description: alarm test
resources:
  cpu_alarm_low:
    type: OS::Ceilometer::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale-up if the last CPU > 50% for 1 minute
      metric: cpu_util
      aggregation_method: min
      granularity: 1
      evaluation_periods: 5
      threshold: 10
      comparison_operator: lt
      resource_type: instance
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}
